apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  creationTimestamp: null
  name: my-tenant
  namespace: default
scheduler:
  name: ""
spec:
  certConfig:
    commonName: ""
    organizationName: []
    dnsNames: []
  console:
    consoleSecret:
      name: my-tenant-console-secret
    image: minio/console:v0.3.14
    metadata:
      creationTimestamp: null
      name: my-tenant
    replicas: 2
    resources: {}
  credsSecret:
    name: my-tenant-creds-secret
  image: minio/minio:RELEASE.2020-09-26T03-44-56Z
  imagePullSecret: {}
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 1
    timeoutSeconds: 1
  mountPath: /export
  requestAutoCert: true
  serviceName: my-tenant-internal-service
  zones:
  - resources: {}
    servers: 2
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 256Mi
      status: {}
    volumesPerServer: 2
status:
  availableReplicas: 0
  currentState: ""

---
apiVersion: v1
data:
  accesskey: Y2U2NTBjYzAtZTU3NC00OTk1LWJkMTMtZjQ2NWQ3NGE5MmVh
  secretkey: YWU0MWRjMWQtNDk2OC00Y2YxLWJiZGYtNGQ4NDY1OGRhNTU4
kind: Secret
metadata:
  creationTimestamp: null
  name: my-tenant-creds-secret
  namespace: default

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: ZmRmOGMxNmEtOTgxZi00ZGQyLWIxYmYtZmVkODIxODA0MGE4
  CONSOLE_HMAC_JWT_SECRET: ZWZlNWVmYTAtMWZmNy00MzAxLWE5NWUtZmNhM2JiZDM3MDIw
  CONSOLE_PBKDF_PASSPHRASE: NTQ5MzA1YzEtODg1ZS00MTkyLTk1YmMtZTdhMWQ0NjRjZWI2
  CONSOLE_PBKDF_SALT: NjgwYzZhZjEtNWQzMS00NTU4LTllZDQtNjQwMGQ1YmVhMTBk
  CONSOLE_SECRET_KEY: MTFlMjFjNWEtNGE4Zi00YjY0LTlmYWYtZWJkM2Y3ZWQ2MDQ2
kind: Secret
metadata:
  creationTimestamp: null
  name: my-tenant-console-secret
  namespace: default

