apiVersion: policy/v1beta1 
kind: PodSecurityPolicy 
metadata: 
  name: privileged-psp 
  annotations: 
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*' 
spec: 
  privileged: true 
  allowedCapabilities: 
  - '*' 
  volumes: 
  - '*' 
  hostNetwork: true 
  hostPorts: 
  - min: 2000 
    max: 65535 
  hostIPC: true 
  hostPID: true 
  allowPrivilegeEscalation: true 
  runAsUser: 
    rule: 'RunAsAny' 
  supplementalGroups: 
    rule: 'RunAsAny' 
  fsGroup: 
    rule: 'RunAsAny' 
