apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding 
metadata: 
  name: privileged-crb 
roleRef: 
  kind: ClusterRole 
  name: privileged-role 
  apiGroup: rbac.authorization.k8s.io 
subjects: 
- kind: Group 
  apiGroup: rbac.authorization.k8s.io 
  name: system:authenticated 
