apiVersion: policy/v1beta1 
kind: PodSecurityPolicy 
metadata: 
  name: specific-user-psp 
spec: 
  privileged: false 
  allowPrivilegeEscalation: false 
  hostNetwork: false 
  hostIPC: false 
  hostPID: false 
  runAsUser: 
    rule: 'MustRunAs' 
    ranges: 
      - min: 1 
        max: 3000 
  readOnlyRootFilesystem: false 
